"""Action alias table for MCP execute endpoint."""
from __future__ import annotations

from typing import Dict


ACTION_ALIASES: Dict[str, str] = {
    "start": "browser_start",
    "install": "browser_install",
    "profiles": "browser_profiles",
    "tabs": "browser_tabs",
    "tabs.open": "browser_tabs_open",
    "tabs.new": "browser_tabs_open",
    "tabs.focus": "browser_tabs_focus",
    "tabs.close": "browser_tabs_close",
    "tabs.delete": "browser_tabs_close",
    "tabs.action": "browser_tabs_action",
    "tabs_open": "browser_tabs_open",
    "tabs_focus": "browser_tabs_focus",
    "tabs_close": "browser_tabs_close",
    "tabs_action": "browser_tabs_action",
    "snapshot": "browser_snapshot",
    "act": "browser_act",
    "wait": "browser_wait",
    "screenshot": "browser_screenshot",
    "pdf": "browser_pdf",
    "console": "browser_console_get",
    "console_get": "browser_console_get",
    "errors": "browser_errors_get",
    "errors_get": "browser_errors_get",
    "requests": "browser_requests_get",
    "requests_get": "browser_requests_get",
    "response_body": "browser_response_body",
    "trace_start": "browser_trace_start",
    "trace_stop": "browser_trace_stop",
    "highlight": "browser_highlight",
    "dialog_arm": "browser_dialog_arm",
    "file_chooser_arm": "browser_file_chooser_arm",
    "download_wait": "browser_download_wait",
    "state": "browser_state",
    "env": "browser_env",
    "close": "browser_close",
    "browser.start": "browser_start",
    "browser.install": "browser_install",
    "browser.profiles": "browser_profiles",
    "browser.tabs": "browser_tabs",
    "browser.tabs_open": "browser_tabs_open",
    "browser.tabs_focus": "browser_tabs_focus",
    "browser.tabs_close": "browser_tabs_close",
    "browser.tabs_action": "browser_tabs_action",
    "browser.tabs.open": "browser_tabs_open",
    "browser.tabs.new": "browser_tabs_open",
    "browser.tabs.focus": "browser_tabs_focus",
    "browser.tabs.close": "browser_tabs_close",
    "browser.tabs.delete": "browser_tabs_close",
    "browser.tabs.action": "browser_tabs_action",
    "browser.snapshot": "browser_snapshot",
    "browser.act": "browser_act",
    "browser.wait": "browser_wait",
    "browser.screenshot": "browser_screenshot",
    "browser.pdf": "browser_pdf",
    "browser.console_get": "browser_console_get",
    "browser.errors_get": "browser_errors_get",
    "browser.requests_get": "browser_requests_get",
    "browser.response_body": "browser_response_body",
    "browser.trace_start": "browser_trace_start",
    "browser.trace_stop": "browser_trace_stop",
    "browser.highlight": "browser_highlight",
    "browser.dialog_arm": "browser_dialog_arm",
    "browser.file_chooser_arm": "browser_file_chooser_arm",
    "browser.download_wait": "browser_download_wait",
    "browser.state": "browser_state",
    "browser.env": "browser_env",
    "browser.close": "browser_close",
}


LEGACY_ACTIONS_NOT_NEEDING_SELECTOR = [
    "goto",
    "setViewport",
    "evaluate",
    "tab",
    "scroll",
    "wait",
    "waitForTimeout",
    "clickAt",
    "click_at_coordinates",
    "fillAt",
    "fill_at_coordinates",
    "expectTrue",
    "expectAttribute",
    "expectCountAtLeast",
    "expectVisible",
    "expectHidden",
]
